package tokenizer

import (
	"encoding/binary"
	"fmt"
	"math"
	"os"
	"strings"
	"unicode/utf8"

	ort "github.com/DavidSche/raven-onnxruntime/ort"
)

// Source identifies where a tokenization bundle came from.
type Source string

const (
	// SourceCached indicates tokenization was loaded from a cache file.
	SourceCached Source = "cached"
	// SourcePlaceholder indicates tokenization was generated by the lightweight fallback tokenizer.
	SourcePlaceholder Source = "placeholder"
)

// Bundle groups the tensors required by the GroundingDINO-style text encoder.
type Bundle struct {
	InputIds          *ort.Value
	AttentionMask     *ort.Value
	TokenTypeIds      *ort.Value
	TextSelfAttnMasks *ort.Value
	PositionIds       *ort.Value
	Source            Source
}

// Destroy releases all tensors in the bundle.
func (b *Bundle) Destroy() {
	if b == nil {
		return
	}
	ort.DestroyValueSlice([]*ort.Value{
		b.InputIds,
		b.AttentionMask,
		b.TokenTypeIds,
		b.TextSelfAttnMasks,
		b.PositionIds,
	})
	b.InputIds = nil
	b.AttentionMask = nil
	b.TokenTypeIds = nil
	b.TextSelfAttnMasks = nil
	b.PositionIds = nil
}

// Acquire tokenizes captions, preferring a cached binary format and falling back to the placeholder tokenizer.
func Acquire(session *ort.Session, captions []string, maxTextLen int) (*Bundle, error) {
	bundle, err := LoadCached(session, captions, maxTextLen)
	if err == nil {
		return bundle, nil
	}
	return Placeholder(session, captions, maxTextLen)
}

// LoadCached loads tokenization from the local cache directory.
//
// The on-disk cache format stores a single-caption bundle (batchSize=1) per
// file. The current architecture has no way to merge multiple per-caption
// cache blobs into one batched Bundle, so multi-caption requests are rejected
// here and the caller (see Acquire) falls back to the Placeholder tokenizer,
// which natively supports batching.
func LoadCached(session *ort.Session, captions []string, maxTextLen int) (*Bundle, error) {
	if len(captions) != 1 {
		return nil, fmt.Errorf("LoadCached only supports a single caption, got %d", len(captions))
	}
	caption := captions[0]
	cachePath := fmt.Sprintf(".token_cache/%s.bin", SanitizeFilename(caption))
	data, err := os.ReadFile(cachePath)
	if err != nil {
		return nil, fmt.Errorf("cache not found: %w", err)
	}
	bundle, err := DeserializeTokenization(session, data, 1, maxTextLen)
	if err != nil {
		return nil, err
	}
	bundle.Source = SourceCached
	return bundle, nil
}

// Placeholder performs a minimal placeholder tokenization.
func Placeholder(session *ort.Session, captions []string, maxTextLen int) (*Bundle, error) {
	if maxTextLen <= 0 {
		return nil, fmt.Errorf("maxTextLen must be positive: %d", maxTextLen)
	}
	batchSize := len(captions)
	if batchSize == 0 {
		batchSize = 1
	}

	seqLen := maxTextLen

	inputIdsData := make([]int64, batchSize*seqLen)
	attentionMaskData := make([]int64, batchSize*seqLen)
	tokenTypeIdsData := make([]int64, batchSize*seqLen)
	positionIdsData := make([]int64, batchSize*seqLen)
	selfAttnData := make([]float32, batchSize*seqLen*seqLen)

	for i := 0; i < batchSize; i++ {
		inputIdsData[i*seqLen] = 101
		caption := ""
		if i < len(captions) {
			caption = captions[i]
		}
		// Use rune count (not byte length) so multi-byte UTF-8 characters are
		// not truncated mid-codepoint.
		runeCount := utf8.RuneCountInString(caption)
		tokenLen := min(runeCount, seqLen-2)
		if tokenLen < 0 {
			tokenLen = 0
		}
		runes := []rune(caption)
		for j := 0; j < tokenLen; j++ {
			inputIdsData[i*seqLen+j+1] = int64(runes[j]) + 1000
		}
		inputIdsData[i*seqLen+tokenLen+1] = 102

		for j := 0; j < tokenLen+2; j++ {
			attentionMaskData[i*seqLen+j] = 1
		}
		for j := 0; j < seqLen; j++ {
			positionIdsData[i*seqLen+j] = int64(j)
		}
		for r := 0; r < seqLen; r++ {
			for c := 0; c < seqLen; c++ {
				idx := i*seqLen*seqLen + r*seqLen + c
				if r == c || (r == 0 && c == 0) || (r > 0 && r <= tokenLen+1 && c > 0 && c <= tokenLen+1) {
					selfAttnData[idx] = 1
				}
			}
		}
	}

	inputIds, err := session.NewTensor([]int64{int64(batchSize), int64(seqLen)}, inputIdsData)
	if err != nil {
		return nil, fmt.Errorf("create input_ids tensor failed: %w", err)
	}

	attentionMask, err := session.NewTensor([]int64{int64(batchSize), int64(seqLen)}, attentionMaskData)
	if err != nil {
		inputIds.Destroy()
		return nil, fmt.Errorf("create attention_mask tensor failed: %w", err)
	}

	tokenTypeIds, err := session.NewTensor([]int64{int64(batchSize), int64(seqLen)}, tokenTypeIdsData)
	if err != nil {
		inputIds.Destroy()
		attentionMask.Destroy()
		return nil, fmt.Errorf("create token_type_ids tensor failed: %w", err)
	}

	textSelfAttnMasks, err := session.NewTensor([]int64{int64(batchSize), int64(seqLen), int64(seqLen)}, selfAttnData)
	if err != nil {
		inputIds.Destroy()
		attentionMask.Destroy()
		tokenTypeIds.Destroy()
		return nil, fmt.Errorf("create text_self_attention_masks tensor failed: %w", err)
	}

	positionIds, err := session.NewTensor([]int64{int64(batchSize), int64(seqLen)}, positionIdsData)
	if err != nil {
		inputIds.Destroy()
		attentionMask.Destroy()
		tokenTypeIds.Destroy()
		textSelfAttnMasks.Destroy()
		return nil, fmt.Errorf("create position_ids tensor failed: %w", err)
	}

	return &Bundle{
		InputIds:          inputIds,
		AttentionMask:     attentionMask,
		TokenTypeIds:      tokenTypeIds,
		TextSelfAttnMasks: textSelfAttnMasks,
		PositionIds:       positionIds,
		Source:            SourcePlaceholder,
	}, nil
}

// TokenizeCaptions tokenizes captions using the explicit Bundle API and returns the raw tensors.
func TokenizeCaptions(session *ort.Session, captions []string, maxTextLen int) (inputIds, attentionMask, tokenTypeIds, textSelfAttnMasks, positionIds *ort.Value, err error) {
	bundle, err := Acquire(session, captions, maxTextLen)
	if err != nil {
		return nil, nil, nil, nil, nil, err
	}
	return bundle.InputIds, bundle.AttentionMask, bundle.TokenTypeIds, bundle.TextSelfAttnMasks, bundle.PositionIds, nil
}

// SimpleTokenize is kept for backward compatibility. Prefer Placeholder.
func SimpleTokenize(session *ort.Session, captions []string, maxTextLen int) (*ort.Value, *ort.Value, *ort.Value, *ort.Value, *ort.Value, error) {
	bundle, err := Placeholder(session, captions, maxTextLen)
	if err != nil {
		return nil, nil, nil, nil, nil, err
	}
	return bundle.InputIds, bundle.AttentionMask, bundle.TokenTypeIds, bundle.TextSelfAttnMasks, bundle.PositionIds, nil
}

// LoadCachedTokenization is kept for backward compatibility. Prefer LoadCached.
func LoadCachedTokenization(session *ort.Session, captions []string, maxTextLen int) (*ort.Value, *ort.Value, *ort.Value, *ort.Value, *ort.Value, error) {
	bundle, err := LoadCached(session, captions, maxTextLen)
	if err != nil {
		return nil, nil, nil, nil, nil, err
	}
	return bundle.InputIds, bundle.AttentionMask, bundle.TokenTypeIds, bundle.TextSelfAttnMasks, bundle.PositionIds, nil
}

// DeserializeTokenization deserializes a cached tokenization blob.
func DeserializeTokenization(session *ort.Session, data []byte, batchSize, maxTextLen int) (*Bundle, error) {
	// Validate parameters and guard against integer overflow in the size
	// computations below. Without these checks, large batchSize/maxTextLen
	// values could overflow int64 and produce a negative expectedSize, which
	// would silently bypass the length validation.
	const maxTextLenLimit = 8192
	if batchSize <= 0 || maxTextLen <= 0 || maxTextLen > maxTextLenLimit {
		return nil, fmt.Errorf("invalid parameters: batchSize=%d maxTextLen=%d", batchSize, maxTextLen)
	}

	B := int64(batchSize)
	L := int64(maxTextLen)

	const int64Size = 8
	const float32Size = 4

	// Overflow checks before multiplying.
	if L > 0 && B > math.MaxInt64/L {
		return nil, fmt.Errorf("batchSize*maxTextLen overflow: batchSize=%d maxTextLen=%d", batchSize, maxTextLen)
	}
	bl := B * L
	if L > 0 && bl > math.MaxInt64/L {
		return nil, fmt.Errorf("batchSize*maxTextLen^2 overflow: batchSize=%d maxTextLen=%d", batchSize, maxTextLen)
	}
	bll := bl * L
	if bll > math.MaxInt64/int64(float32Size) {
		return nil, fmt.Errorf("tokenization size overflow: batchSize=%d maxTextLen=%d", batchSize, maxTextLen)
	}

	inputIdsSize := bl * int64(int64Size)
	attentionMaskSize := bl * int64(int64Size)
	tokenTypeIdsSize := bl * int64(int64Size)
	selfAttnSize := bll * int64(float32Size)
	positionIdsSize := bl * int64(int64Size)

	expectedSize := inputIdsSize + attentionMaskSize + tokenTypeIdsSize + selfAttnSize + positionIdsSize
	if int64(len(data)) < expectedSize {
		return nil, fmt.Errorf("tokenization data too short: got %d want %d", len(data), expectedSize)
	}

	offset := 0
	inputIdsCount := bl

	readInt64 := func(count int64, size int) []int64 {
		values := make([]int64, count)
		for i := 0; i < int(count); i++ {
			values[i] = int64(binary.LittleEndian.Uint64(data[offset+i*size:]))
		}
		offset += int(count) * size
		return values
	}
	readFloat32 := func(count int64, size int) []float32 {
		values := make([]float32, count)
		for i := 0; i < int(count); i++ {
			values[i] = math.Float32frombits(binary.LittleEndian.Uint32(data[offset+i*size:]))
		}
		offset += int(count) * size
		return values
	}

	inputIdsData := readInt64(inputIdsCount, int64Size)
	attentionMaskData := readInt64(inputIdsCount, int64Size)
	tokenTypeIdsData := readInt64(inputIdsCount, int64Size)
	selfAttnData := readFloat32(bll, float32Size)
	positionIdsData := readInt64(inputIdsCount, int64Size)

	inputIds, err := session.NewTensor([]int64{B, L}, inputIdsData)
	if err != nil {
		return nil, err
	}
	attentionMask, err := session.NewTensor([]int64{B, L}, attentionMaskData)
	if err != nil {
		inputIds.Destroy()
		return nil, err
	}
	tokenTypeIds, err := session.NewTensor([]int64{B, L}, tokenTypeIdsData)
	if err != nil {
		inputIds.Destroy()
		attentionMask.Destroy()
		return nil, err
	}
	textSelfAttnMasks, err := session.NewTensor([]int64{B, L, L}, selfAttnData)
	if err != nil {
		inputIds.Destroy()
		attentionMask.Destroy()
		tokenTypeIds.Destroy()
		return nil, err
	}
	positionIds, err := session.NewTensor([]int64{B, L}, positionIdsData)
	if err != nil {
		inputIds.Destroy()
		attentionMask.Destroy()
		tokenTypeIds.Destroy()
		textSelfAttnMasks.Destroy()
		return nil, err
	}

	return &Bundle{
		InputIds:          inputIds,
		AttentionMask:     attentionMask,
		TokenTypeIds:      tokenTypeIds,
		TextSelfAttnMasks: textSelfAttnMasks,
		PositionIds:       positionIds,
		Source:            SourceCached,
	}, nil
}

// SanitizeFilename creates a cache-file-safe name.
func SanitizeFilename(s string) string {
	s = strings.ReplaceAll(s, " ", "_")
	s = strings.ReplaceAll(s, "/", "_")
	s = strings.ReplaceAll(s, "\\", "_")
	s = strings.ReplaceAll(s, ":", "_")
	s = strings.ReplaceAll(s, ".", "_")
	s = strings.ReplaceAll(s, "?", "_")
	if len(s) > 100 {
		s = s[:100]
	}
	return s
}
